//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sheet1_
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Number { get; set; }
        public string Name_URL { get; set; }
        public string Name { get; set; }
        public string @class { get; set; }
        public string class1 { get; set; }
        public string Date { get; set; }
        public string Status_URL { get; set; }
        public string Status { get; set; }
    }
}
