//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI3
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbUser
    {
        public int UserID { get; set; }
        public string Имя { get; set; }
        public string Фамилия { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
    }
}
